/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package elmsort;

import java.util.ArrayList;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author dhunter3
 */
public class ElementsForm extends javax.swing.JFrame {

    /**
     * Creates new form ElementsForm
     */
    public ElementsForm() {
        initComponents();
        SetText();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        ByName = new javax.swing.JButton();
        ByWeight = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        TextArea1 = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        ByName.setText("By Name");
        ByName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ByNameActionPerformed(evt);
            }
        });

        ByWeight.setText("By Weight");
        ByWeight.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ByWeightActionPerformed(evt);
            }
        });

        TextArea1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Name", "Abbreviation", "Atomic Number", "Weight"
            }
        ));
        jScrollPane1.setViewportView(TextArea1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 637, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 27, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(ByName, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(ByWeight, javax.swing.GroupLayout.Alignment.TRAILING))
                .addGap(42, 42, 42))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(51, 51, 51)
                .addComponent(ByName)
                .addGap(18, 18, 18)
                .addComponent(ByWeight)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 552, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void ByNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ByNameActionPerformed
        // TODO add your handling code here:
        ElmSort elements = new ElmSort();
        ArrayList<ElementNode> el = elements.getNameSorted();
        DefaultTableModel model = (DefaultTableModel) TextArea1.getModel();
        while (model.getRowCount() > 0) {
            model.removeRow(0);
        }
        Object[] rowData = new Object[4];
        for (int i = 0; i < el.size(); i++) {
            rowData[0] = el.get(i).getName();
            rowData[1] = el.get(i).getAbbr();
            rowData[2] = el.get(i).getNumber();
            rowData[3] = el.get(i).getWeight();
            model.addRow(rowData);
        }
    }//GEN-LAST:event_ByNameActionPerformed

    private void ByWeightActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ByWeightActionPerformed
        // TODO add your handling code here:
        ElmSort elements = new ElmSort();
        ArrayList<ElementNode> el = elements.getWeightSorted();
        DefaultTableModel model = (DefaultTableModel) TextArea1.getModel();
        model.setRowCount(0);
        Object[] rowData = new Object[4];
        for (int i = 0; i < el.size(); i++) {
            rowData[0] = el.get(i).getName();
            rowData[1] = el.get(i).getAbbr();
            rowData[2] = el.get(i).getNumber();
            rowData[3] = el.get(i).getWeight();
            model.addRow(rowData);
        }
    }//GEN-LAST:event_ByWeightActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {

        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ElementsForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ElementsForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ElementsForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ElementsForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ElementsForm().setVisible(true);
            }

        });

    }

    public void SetText() {
        ElmSort elements = new ElmSort();
        ArrayList<ElementNode> el = elements.getElements();
        DefaultTableModel model = (DefaultTableModel) TextArea1.getModel();
        Object[] rowData = new Object[4];
        for (int i = 0; i < el.size(); i++) {
            rowData[0] = el.get(i).getName();
            rowData[1] = el.get(i).getAbbr();
            rowData[2] = el.get(i).getNumber();
            rowData[3] = el.get(i).getWeight();
            model.addRow(rowData);
        }
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton ByName;
    private javax.swing.JButton ByWeight;
    private javax.swing.JTable TextArea1;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
